main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

#inicialização
app = Flask (__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

#execução
app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES
#inicia o blueprint
cliente_route = Blueprint('cliente', __name__)

#definindo as rotas
@cliente_route.route('/')
def lista_clientes():
    return render_template('lista_clientes.html', clientes=CLIENTES)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    
    data = request.json
    
    novo_usuario = {
        "id": len(CLIENTES)+1,
        "nome": data['nome'],
        "email": data['email'],
    }

    CLIENTES.append(novo_usuario)

    return render_template('item_cliente.html', cliente=novo_usuario)

@cliente_route.route('/new')
def form_cliente(): 
    return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    cliente = list(filter(lambda c: c['id'] == cliente_id, CLIENTES))[0]
    return render_template('detalhe_cliente.html', cliente=cliente)

@cliente_route.route('/<int:cliente_id>/edit')
def form_editaCliente(cliente_id):
    cliente = None
    for c in CLIENTES:
        if c['id'] == cliente_id:
            cliente = c

    return render_template('form_cliente.html', cliente=cliente)

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_dadoCliente(cliente_id):
    cliente_editado = None
    data = request.json
    for c in CLIENTES:
        if c['id'] == cliente_id:
            c['nome'] = data['nome']
            c['email'] = data['email']

            cliente_editado = c
    return render_template('item_cliente.html', cliente=cliente_editado)

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
    global CLIENTES
    CLIENTES = [ c for c in CLIENTES if c['id'] != cliente_id]
    return {'deleted':'ok'}

routes/home.py
from flask import Blueprint, render_template

#inicia o blueprint
home_route = Blueprint('home', __name__)

#definindo as rotas
@home_route.route('/')
def home():
    return render_template('index.html')

templates/detalhe_cliente.html
<ul>
    <li>ID: {{cliente.id}}</li>
    <li>Nome: {{cliente.nome}}</li>
    <li>Email: {{cliente.email}}</li>
</ul>

templates/form_cliente.html
<form class="c-form" {% if cliente %} 
    action="{{ url_for('cliente.atualizar_dadoCliente', cliente_id=cliente.id) }}"
  {% else %}
    action="{{ url_for('cliente.inserir_cliente') }}"
  {% endif %}

  method="{% if cliente %}PUT{% else %}POST{% endif %}"

  {%if cliente %}
    c-swap="#cliente={{cliente.id}}" 
  {% else %}
    c-append="#lista_clientes" 
  {% endif%}>
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome" {% if cliente %} value="{{cliente.nome}}"{% endif %}>
    </div>

    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="text" class="form-control" name="email" {% if cliente %} value="{{cliente.email}}"{% endif %}>
    </div>

    <button type="submit" class="btn btn-primary" c-reload=True>
      {% if cliente %}Salvar{% else %} Criar{% endif %} 
    </button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1 class="text-center">Gestão de Clientes</h1>

    <div class="container">
      <!--Formulario add cliente-->
      <div id="form-cliente" c-container="{{ url_for('cliente.form_cliente')}}"></div>

      <hr>

      <!-- Lista de clientes-->
      <h2>Lista de clientes</h2>
      <div c-container="{{ url_for('cliente.lista_clientes')}}" ></div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="exibir-cliente"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='cru.js') }}"></script>
</body>
</html>

templates/item_cliente.html
<tr id="cliente={{cliente.id}}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-secondary" c-get="{{ url_for('cliente.detalhe_cliente', cliente_id=cliente.id )}}" c-target="#exibir-cliente" data-bs-toggle="modal" data-bs-target="#exampleModal">Vizualizar</button>
        <button class="btn btn-primary" c-get="{{ url_for('cliente.form_editaCliente', cliente_id=cliente.id )}}" c-target="#form-cliente">Editar</button>
        <button class="btn btn-danger" c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id) }}" c-remove-closest="tr">Deletar</button>
    </td>
</tr>

templates/lista_clientes.html
<table class="table" c-reload=True>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista_clientes">

        {% for cliente in clientes %}
           {% include 'item_cliente.html' %}
        {% endfor %}

    </tbody>
  </table>